# Generated by Django 6.0.2 on 2026-03-02 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Компьютерная техника', 'Компьютерная техника'), ('Мобильная техника', 'Мобильная техника'), ('Аудио и видео', 'Аудио и видео'), ('Игровая техника', 'Игровая техника'), ('Бытовая техника', 'Бытовая техника'), ('Умные устройства', 'Умные устройства'), ('Фото и видео', 'Фото и видео'), ('Сетевое оборудование', 'Сетевое оборудование'), ('Аксессуары', 'Аксессуары')], default=1),
            preserve_default=False,
        ),
    ]
